//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSSimposio
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSSimposio.ArquivosSimposioSoap")]
    public interface ArquivosSimposioSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/caminho", ReplyAction="*")]
        System.Threading.Tasks.Task<WSSimposio.caminhoResponse> caminhoAsync(WSSimposio.caminhoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SalvarArquivo", ReplyAction="*")]
        System.Threading.Tasks.Task<WSSimposio.SalvarArquivoResponse> SalvarArquivoAsync(WSSimposio.SalvarArquivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BaixarArquivo", ReplyAction="*")]
        System.Threading.Tasks.Task<WSSimposio.BaixarArquivoResponse> BaixarArquivoAsync(WSSimposio.BaixarArquivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SalvarArquivoSimposio", ReplyAction="*")]
        System.Threading.Tasks.Task<WSSimposio.SalvarArquivoSimposioResponse> SalvarArquivoSimposioAsync(WSSimposio.SalvarArquivoSimposioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BaixarArquivoSimposio", ReplyAction="*")]
        System.Threading.Tasks.Task<WSSimposio.BaixarArquivoSimposioResponse> BaixarArquivoSimposioAsync(WSSimposio.BaixarArquivoSimposioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterTrabalhosEspecificos", ReplyAction="*")]
        System.Threading.Tasks.Task<WSSimposio.ObterTrabalhosEspecificosResponse> ObterTrabalhosEspecificosAsync(WSSimposio.ObterTrabalhosEspecificosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class caminhoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="caminho", Namespace="http://tempuri.org/", Order=0)]
        public WSSimposio.caminhoRequestBody Body;
        
        public caminhoRequest()
        {
        }
        
        public caminhoRequest(WSSimposio.caminhoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class caminhoRequestBody
    {
        
        public caminhoRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class caminhoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="caminhoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSSimposio.caminhoResponseBody Body;
        
        public caminhoResponse()
        {
        }
        
        public caminhoResponse(WSSimposio.caminhoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class caminhoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string caminhoResult;
        
        public caminhoResponseBody()
        {
        }
        
        public caminhoResponseBody(string caminhoResult)
        {
            this.caminhoResult = caminhoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SalvarArquivoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SalvarArquivo", Namespace="http://tempuri.org/", Order=0)]
        public WSSimposio.SalvarArquivoRequestBody Body;
        
        public SalvarArquivoRequest()
        {
        }
        
        public SalvarArquivoRequest(WSSimposio.SalvarArquivoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SalvarArquivoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NomeArquivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] Arquivo;
        
        public SalvarArquivoRequestBody()
        {
        }
        
        public SalvarArquivoRequestBody(string NomeArquivo, byte[] Arquivo)
        {
            this.NomeArquivo = NomeArquivo;
            this.Arquivo = Arquivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SalvarArquivoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SalvarArquivoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSSimposio.SalvarArquivoResponseBody Body;
        
        public SalvarArquivoResponse()
        {
        }
        
        public SalvarArquivoResponse(WSSimposio.SalvarArquivoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SalvarArquivoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SalvarArquivoResult;
        
        public SalvarArquivoResponseBody()
        {
        }
        
        public SalvarArquivoResponseBody(string SalvarArquivoResult)
        {
            this.SalvarArquivoResult = SalvarArquivoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BaixarArquivoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BaixarArquivo", Namespace="http://tempuri.org/", Order=0)]
        public WSSimposio.BaixarArquivoRequestBody Body;
        
        public BaixarArquivoRequest()
        {
        }
        
        public BaixarArquivoRequest(WSSimposio.BaixarArquivoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BaixarArquivoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NomeArquivo;
        
        public BaixarArquivoRequestBody()
        {
        }
        
        public BaixarArquivoRequestBody(string NomeArquivo)
        {
            this.NomeArquivo = NomeArquivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BaixarArquivoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BaixarArquivoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSSimposio.BaixarArquivoResponseBody Body;
        
        public BaixarArquivoResponse()
        {
        }
        
        public BaixarArquivoResponse(WSSimposio.BaixarArquivoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BaixarArquivoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] BaixarArquivoResult;
        
        public BaixarArquivoResponseBody()
        {
        }
        
        public BaixarArquivoResponseBody(byte[] BaixarArquivoResult)
        {
            this.BaixarArquivoResult = BaixarArquivoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SalvarArquivoSimposioRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SalvarArquivoSimposio", Namespace="http://tempuri.org/", Order=0)]
        public WSSimposio.SalvarArquivoSimposioRequestBody Body;
        
        public SalvarArquivoSimposioRequest()
        {
        }
        
        public SalvarArquivoSimposioRequest(WSSimposio.SalvarArquivoSimposioRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SalvarArquivoSimposioRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NomeArquivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] Arquivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TipoArquivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CodEvento;
        
        public SalvarArquivoSimposioRequestBody()
        {
        }
        
        public SalvarArquivoSimposioRequestBody(string NomeArquivo, byte[] Arquivo, string TipoArquivo, string CodEvento)
        {
            this.NomeArquivo = NomeArquivo;
            this.Arquivo = Arquivo;
            this.TipoArquivo = TipoArquivo;
            this.CodEvento = CodEvento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SalvarArquivoSimposioResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SalvarArquivoSimposioResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSSimposio.SalvarArquivoSimposioResponseBody Body;
        
        public SalvarArquivoSimposioResponse()
        {
        }
        
        public SalvarArquivoSimposioResponse(WSSimposio.SalvarArquivoSimposioResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SalvarArquivoSimposioResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SalvarArquivoSimposioResult;
        
        public SalvarArquivoSimposioResponseBody()
        {
        }
        
        public SalvarArquivoSimposioResponseBody(string SalvarArquivoSimposioResult)
        {
            this.SalvarArquivoSimposioResult = SalvarArquivoSimposioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BaixarArquivoSimposioRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BaixarArquivoSimposio", Namespace="http://tempuri.org/", Order=0)]
        public WSSimposio.BaixarArquivoSimposioRequestBody Body;
        
        public BaixarArquivoSimposioRequest()
        {
        }
        
        public BaixarArquivoSimposioRequest(WSSimposio.BaixarArquivoSimposioRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BaixarArquivoSimposioRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NomeArquivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TipoArquivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CodEvento;
        
        public BaixarArquivoSimposioRequestBody()
        {
        }
        
        public BaixarArquivoSimposioRequestBody(string NomeArquivo, string TipoArquivo, string CodEvento)
        {
            this.NomeArquivo = NomeArquivo;
            this.TipoArquivo = TipoArquivo;
            this.CodEvento = CodEvento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BaixarArquivoSimposioResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BaixarArquivoSimposioResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSSimposio.BaixarArquivoSimposioResponseBody Body;
        
        public BaixarArquivoSimposioResponse()
        {
        }
        
        public BaixarArquivoSimposioResponse(WSSimposio.BaixarArquivoSimposioResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BaixarArquivoSimposioResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] BaixarArquivoSimposioResult;
        
        public BaixarArquivoSimposioResponseBody()
        {
        }
        
        public BaixarArquivoSimposioResponseBody(byte[] BaixarArquivoSimposioResult)
        {
            this.BaixarArquivoSimposioResult = BaixarArquivoSimposioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterTrabalhosEspecificosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterTrabalhosEspecificos", Namespace="http://tempuri.org/", Order=0)]
        public WSSimposio.ObterTrabalhosEspecificosRequestBody Body;
        
        public ObterTrabalhosEspecificosRequest()
        {
        }
        
        public ObterTrabalhosEspecificosRequest(WSSimposio.ObterTrabalhosEspecificosRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObterTrabalhosEspecificosRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSSimposio.ArrayOfString nomeTrabalho;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string apresentacao;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int codEvento;
        
        public ObterTrabalhosEspecificosRequestBody()
        {
        }
        
        public ObterTrabalhosEspecificosRequestBody(WSSimposio.ArrayOfString nomeTrabalho, string apresentacao, int codEvento)
        {
            this.nomeTrabalho = nomeTrabalho;
            this.apresentacao = apresentacao;
            this.codEvento = codEvento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterTrabalhosEspecificosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterTrabalhosEspecificosResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSSimposio.ObterTrabalhosEspecificosResponseBody Body;
        
        public ObterTrabalhosEspecificosResponse()
        {
        }
        
        public ObterTrabalhosEspecificosResponse(WSSimposio.ObterTrabalhosEspecificosResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObterTrabalhosEspecificosResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSSimposio.ArrayOfString ObterTrabalhosEspecificosResult;
        
        public ObterTrabalhosEspecificosResponseBody()
        {
        }
        
        public ObterTrabalhosEspecificosResponseBody(WSSimposio.ArrayOfString ObterTrabalhosEspecificosResult)
        {
            this.ObterTrabalhosEspecificosResult = ObterTrabalhosEspecificosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface ArquivosSimposioSoapChannel : WSSimposio.ArquivosSimposioSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class ArquivosSimposioSoapClient : System.ServiceModel.ClientBase<WSSimposio.ArquivosSimposioSoap>, WSSimposio.ArquivosSimposioSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ArquivosSimposioSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ArquivosSimposioSoapClient.GetBindingForEndpoint(endpointConfiguration), ArquivosSimposioSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ArquivosSimposioSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ArquivosSimposioSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ArquivosSimposioSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ArquivosSimposioSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ArquivosSimposioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSSimposio.caminhoResponse> WSSimposio.ArquivosSimposioSoap.caminhoAsync(WSSimposio.caminhoRequest request)
        {
            return base.Channel.caminhoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSSimposio.caminhoResponse> caminhoAsync()
        {
            WSSimposio.caminhoRequest inValue = new WSSimposio.caminhoRequest();
            inValue.Body = new WSSimposio.caminhoRequestBody();
            return ((WSSimposio.ArquivosSimposioSoap)(this)).caminhoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSSimposio.SalvarArquivoResponse> WSSimposio.ArquivosSimposioSoap.SalvarArquivoAsync(WSSimposio.SalvarArquivoRequest request)
        {
            return base.Channel.SalvarArquivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSSimposio.SalvarArquivoResponse> SalvarArquivoAsync(string NomeArquivo, byte[] Arquivo)
        {
            WSSimposio.SalvarArquivoRequest inValue = new WSSimposio.SalvarArquivoRequest();
            inValue.Body = new WSSimposio.SalvarArquivoRequestBody();
            inValue.Body.NomeArquivo = NomeArquivo;
            inValue.Body.Arquivo = Arquivo;
            return ((WSSimposio.ArquivosSimposioSoap)(this)).SalvarArquivoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSSimposio.BaixarArquivoResponse> WSSimposio.ArquivosSimposioSoap.BaixarArquivoAsync(WSSimposio.BaixarArquivoRequest request)
        {
            return base.Channel.BaixarArquivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSSimposio.BaixarArquivoResponse> BaixarArquivoAsync(string NomeArquivo)
        {
            WSSimposio.BaixarArquivoRequest inValue = new WSSimposio.BaixarArquivoRequest();
            inValue.Body = new WSSimposio.BaixarArquivoRequestBody();
            inValue.Body.NomeArquivo = NomeArquivo;
            return ((WSSimposio.ArquivosSimposioSoap)(this)).BaixarArquivoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSSimposio.SalvarArquivoSimposioResponse> WSSimposio.ArquivosSimposioSoap.SalvarArquivoSimposioAsync(WSSimposio.SalvarArquivoSimposioRequest request)
        {
            return base.Channel.SalvarArquivoSimposioAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSSimposio.SalvarArquivoSimposioResponse> SalvarArquivoSimposioAsync(string NomeArquivo, byte[] Arquivo, string TipoArquivo, string CodEvento)
        {
            WSSimposio.SalvarArquivoSimposioRequest inValue = new WSSimposio.SalvarArquivoSimposioRequest();
            inValue.Body = new WSSimposio.SalvarArquivoSimposioRequestBody();
            inValue.Body.NomeArquivo = NomeArquivo;
            inValue.Body.Arquivo = Arquivo;
            inValue.Body.TipoArquivo = TipoArquivo;
            inValue.Body.CodEvento = CodEvento;
            return ((WSSimposio.ArquivosSimposioSoap)(this)).SalvarArquivoSimposioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSSimposio.BaixarArquivoSimposioResponse> WSSimposio.ArquivosSimposioSoap.BaixarArquivoSimposioAsync(WSSimposio.BaixarArquivoSimposioRequest request)
        {
            return base.Channel.BaixarArquivoSimposioAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSSimposio.BaixarArquivoSimposioResponse> BaixarArquivoSimposioAsync(string NomeArquivo, string TipoArquivo, string CodEvento)
        {
            WSSimposio.BaixarArquivoSimposioRequest inValue = new WSSimposio.BaixarArquivoSimposioRequest();
            inValue.Body = new WSSimposio.BaixarArquivoSimposioRequestBody();
            inValue.Body.NomeArquivo = NomeArquivo;
            inValue.Body.TipoArquivo = TipoArquivo;
            inValue.Body.CodEvento = CodEvento;
            return ((WSSimposio.ArquivosSimposioSoap)(this)).BaixarArquivoSimposioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSSimposio.ObterTrabalhosEspecificosResponse> WSSimposio.ArquivosSimposioSoap.ObterTrabalhosEspecificosAsync(WSSimposio.ObterTrabalhosEspecificosRequest request)
        {
            return base.Channel.ObterTrabalhosEspecificosAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSSimposio.ObterTrabalhosEspecificosResponse> ObterTrabalhosEspecificosAsync(WSSimposio.ArrayOfString nomeTrabalho, string apresentacao, int codEvento)
        {
            WSSimposio.ObterTrabalhosEspecificosRequest inValue = new WSSimposio.ObterTrabalhosEspecificosRequest();
            inValue.Body = new WSSimposio.ObterTrabalhosEspecificosRequestBody();
            inValue.Body.nomeTrabalho = nomeTrabalho;
            inValue.Body.apresentacao = apresentacao;
            inValue.Body.codEvento = codEvento;
            return ((WSSimposio.ArquivosSimposioSoap)(this)).ObterTrabalhosEspecificosAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ArquivosSimposioSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ArquivosSimposioSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ArquivosSimposioSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://www.siu.univale.br/WSSimposio/Service.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ArquivosSimposioSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://www.siu.univale.br/WSSimposio/Service.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ArquivosSimposioSoap,
            
            ArquivosSimposioSoap12,
        }
    }
}
